name: Deploy Terraform on AWS

on:
  workflow_dispatch:  # Only runs when manually triggered in Github web UI

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.10.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # The contents of the .env file are saved into a single secret in the remote github repo,
      # which are then read and dump into a .env file in the action's context 
      - name: Create .env File
        run: |
          echo "${{ secrets.ENV_FILE_CONTENTS }}" > .env
          tree
      
      # Construct the google_credentials.json file in a similar way as the .env file, it's saved as a string
      - name: Create google_credentials.json File
        run: |
          echo "${{ secrets.GOOGLE_CREDENTIALS_JSON }}" > google_credentials.json

      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11' 

      - name: Run Shell Script & Terraform Apply
        run: |
          cd deployment/
          # This script reads from .env, exports the env variables with TF_VAR_ prefix and 
          # packages the required python packages for the Lambda function layer
          source scripts/package.sh
          terraform init
          terraform plan
          terraform apply -auto-approve
        shell: bash
